#!/bin/bash

# Add Starship to local host
curl -sS https://starship.rs/install.sh | sh -s -- -y

# Create directory for dotfiles
mkdir -p ~/.config

# Link dotfiles to home directory
link_dot_file() {
  local src="$1"
  local dest="$2"
  ln -sf "$src" "$dest"
  echo "Linked: $dest"
}

dotfiles=("bashrc" "vimrc" "tmux.conf")

for file in "${dotfiles[@]}"; do
  link_dot_file "$HOME/dotfiles/$file" "$HOME/.$file"
done

ln -sf ~/dotfiles/starship.toml ~/.config/starship.toml
ln -sf ~/dotfiles/local ~/.local

echo "Dotfiles linked...Welcome J Lew! Run source ~/.bashrc now."
