#!/bin/bash

# Add Starship to local host
curl -sS https://starship.rs/install.sh | sh -s -- -y

# Create directory for dotfiles
mkdir -p ~/.config

# Link dotfiles to home directory
ln -sf ~/dotfiles/bashrc ~/.bashrc
ln -sf ~/dotfiles/vimrc ~/.vimrc
ln -sf ~/dotfiles/starship.toml ~/.config/starship.toml

# Clear the screen and prompt
clear

echo "Dotfiles linked...Welcome J Lew! Run source ~/.bashrc now."
