# Enhanced colors
set -g default-terminal 'screen-256color'

# Use of mouse
set -g mouse on

# Start windows and panes at #1 instead of #0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# vim like settings
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Set vi-mode
set-window-option -g mode-keys vi

# Keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Reload config
unbind r
bind r source-file ~/.tmux.conf

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

# Dracula Configuration
set -g @dracula-plugins "battery network weather"
set -g @dracula-show-left-icon session
set -g @dracula-transparent-powerline-bg false
set -g @dracula-weather-location "Houston, Texas"

# Status Bar Configuration
set-option -g status-position top

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
