# Enhanced colors
set -g default-terminal 'tmux-256color'

# Use of mouse
set -g mouse on

# Status Bar Configuration
set-option -g status-position top

# Start windows and panes at #1 instead of #0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# vim like settings
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Set vi-mode
set-window-option -g mode-keys vi

# Keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Reload config
unbind r
bind r source-file ~/.tmux.conf

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'dracula/tmux'
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'tmux-plugins/tmux-yank'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Dracula Configuration
# set -g @dracula-plugins "battery network weather"
# set -g @dracula-show-left-icon session
# set -g @dracula-transparent-powerline-bg false
# set -g @dracula-show-ssh-only-when-connected true
# set -g @dracula-battery-label "🦇 "
# set -g @dracula-fixed-location "Houston"
# set -g @dracula-transparent-powerline-bg true

# Dracula color configurations
# set -g @dracula-attached-clients-colors "cyan dark_gray"
# set -g @dracula-battery-colors "green dark_gray"
# set -g @dracula-continuum-colors "cyan dark_gray"
# set -g @dracula-cpu-usage-colors "orange dark_gray"
# set -g @dracula-custom-plugin-colors "cyan dark_gray"
# set -g @dracula-cwd-colors "dark_gray white"
# set -g @dracula-fossil-colors "green dark_gray"
# set -g @dracula-git-colors "green dark_gray"
# set -g @dracula-gpu-power-draw-colors "green dark_gray"
# set -g @dracula-gpu-ram-usage-colors "cyan dark_gray"
# set -g @dracula-gpu-usage-colors "pink dark_gray"
# set -g @dracula-hg-colors "green dark_gray"
# set -g @dracula-kubernetes-context-colors "cyan dark_gray"
# set -g @dracula-libre-colors "white dark_gray"
# set -g @dracula-mpc-colors "green dark_gray"
# set -g @dracula-network-bandwidth-colors "cyan dark_gray"
# set -g @dracula-network-colors "cyan dark_gray"
# set -g @dracula-network-ping-colors "cyan dark_gray"
# set -g @dracula-network-vpn-colors "cyan dark_gray"
# set -g @dracula-playerctl-colors "green dark_gray"
# set -g @dracula-ram-usage-colors "cyan dark_gray"
# set -g @dracula-spotify-tui-colors "green dark_gray"
# set -g @dracula-ssh-session-colors "green dark_gray"
# set -g @dracula-synchronize-panes-colors "cyan dark_gray"
# set -g @dracula-terraform-colors "light_purple dark_gray"
# set -g @dracula-time-colors "dark_purple white"
# set -g @dracula-tmux-ram-usage-colors "cyan dark_gray"
# set -g @dracula-weather-colors "dark_purple white"

# set -g @dracula-colors " white='#f8f8f2' gray='#44475a' dark_gray='#282a36' light_purple='#bd93f9' dark_purple='#a22ccd' cyan='#218fdb' green='#50fa7b' orange='#ffb86c' red='#ff5555' pink='#ff79c6' yellow='#f1fa8c' "

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
